### PR TITLE
Added the feature to select the destination folder

### LINKED ISSUE #12: Feature request: select folder for decrypted file
@jkotra, unlockR is a lightweight and extremely useful app!

It would be great if we could select a folder to save the decrypted file in.

### PR DESCRIPTION
**Pull request by soumyaDghosh**
Closes #12

### CODE REVIEW

**Comment by jkotra** [comment]
is this complete PR? I don't see any changes in `main.c` where signal callback needs to be changed. I also expect a overview at end end to display the decryption status of each file in the folder.

Maybe I'm missing something, could you please provide instructions to test the functionality of this PR?

Thanks.

**Comment by soumyaDghosh** [comment]
I did nothing extra, as I thought your design might not suit it. 

What I did was, when the Decrypt button is clicked, I opened a Gtk.FileDialog, where the user will select folder. Then, it'll simply decrypt to that folder and show it to the user.

[Screencast from 2023-10-10 14-03-14.webm](https://github.com/jkotra/unlockr/assets/72045785/f6e9ecaf-07b3-45cf-97b0-64d1c159bb85)

**Comment by jkotra** [comment]
> I did nothing extra, as I thought your design might not suit it.
> 
> What I did was, when the Decrypt button is clicked, I opened a Gtk.FileDialog, where the user will select folder. Then, it'll simply decrypt to that folder and show it to the user.
> Screencast.from.2023-10-10.14-03-14.webm

Thanks! 

I understand your work now.
will get back to you soon with suggestions (if any).

Regards.

**Comment by soumyaDghosh** [comment]
@jkotra any way to connect with you personally?

**Comment by jkotra** [comment]
closed in favor of #16. my PR implements menu option to toggle save to folder option and tricky windows integration. I think it goes without saying that default behavior should not be changed. Appreciate your effort though, Thanks.

**Comment by jkotra** [comment]
> @jkotra any way to connect with you personally?

you can contact me at [jagadeesh@stdin.top](mailto:jagadeesh@stdin.top).

**Pull request closed without merging**
